# Use Node.js version 21
FROM node:21

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (or yarn.lock) into the container
COPY package*.json ./
COPY yarn.lock ./

# Install dependencies in the container
RUN yarn install

# Copy the rest of your app's source code into the container
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Command to run your app
CMD ["yarn", "dev"]